name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  merge-c-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge C branch
        run: |
          git config --global user.email "4975214@qq.com"
          git config --global user.name "automerge"
          git checkout main
          echo 'this is an add' > file.txt
          git add .
          git commit -m 'committed by bot'
          # git merge C
          git push origin main
