name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  merge-c-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge C branch
        run: |
          cd $GITHUB_WORKSPACE  # 切换到代码仓库的根目录
          git checkout main
          git merge merge
          git push origin main
