name: My Workflow

# on:
#   repository_dispatch:
#     types:
#       - update-merge
on:
  push:
    branches:
      - new

env:
  MY_REPO: https://iceshoesss:${{secrets.GITHUB_TOKEN}}@github.com/iceshoesss/test.git
  MY_BRANCH: new
  MASTER_REPO: https://github.com/LegacyGwent/LegacyGwent.git
  MASTER_BRANCH: diy

jobs:
  merge-c-branch:
    runs-on: ubuntu-latest

    steps:
       - run: |
          git clone ${{env.MASTER_REPO}} -b ${{env.MASTER_BRANCH}} tmp
          cd tmp
          git config --global user.email "4975214@qq.com"
          git config --global user.name "automerge"
          git config pull.rebase false
          git pull ${{env.MY_REPO}} ${{env.MY_BRANCH}}
          git push